# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Test
on: [push, pull_request]

jobs:
  test:
    strategy:
      fail-fast: false # To see all versions that fail.
      matrix:
        os: ["ubuntu", "windows", "macos"]
        python: ["3.7", "3.8", "3.9", "3.10"] # https://devguide.python.org/versions/#versions

    runs-on: ${{ matrix.os }}-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}
          cache: 'pip'

      - name: Prepare environment
        run: |
          python -m pip install --upgrade pip

      - run: make depend
      - run: make test
