# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Test
on: [push, pull_request]

jobs:
  test:
    strategy:
      fail-fast: false # To see all versions that fail.
      matrix:
        os: ["ubuntu", "windows", "macos"]
        python: ["3.7", "3.8", "3.9", "3.10", "3.11", "3.12"] # https://devguide.python.org/versions/#versions
        exclude:
        - os: "macos"
          python: "3.7" # Prevent "The version '3.7' with architecture 'arm64' was not found for macOS 14.4.1"
        - os: "ubuntu"
          python: "3.7" # Python 3.7 is not available in ubuntu-latest i.e. version 24.04
        include:
        - os: "windows-arm64"
          runner: "windows-11-arm" # Python for Windows ARM64 is available from 3.11
          python: "3.12"
    runs-on: ${{ matrix.runner || format('{0}-latest', matrix.os) }}

    steps:
      - uses: actions/checkout@v7

      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v7
        with:
          python-version: ${{ matrix.python }}
          cache: 'pip'

      - name: Prepare environment
        run: |
          python -m pip install --upgrade pip

      - run: make depend
      - run: make test
